import tracemalloc
import pandas as pd
import dask.dataframe as dd
import time

def tracing_start():
    tracemalloc.stop()
    # print("nTracing Status : ", tracemalloc.is_tracing())
    tracemalloc.start()
    # print("Tracing Status : ", tracemalloc.is_tracing())


def tracing_mem():
    first_size, first_peak = tracemalloc.get_traced_memory()
    peak = first_peak/(1024*1024)
    return(peak)
    # print("Peak Size in MB - ", peak)

weaponList = {
    "alternator": {
        "desc": "Twin Barrel SMG.",
        "longdesc": "The Alternator (also referred to as the SP-14 Hatchet in concept art) is a Pilot anti-personnel twin-barrel submachine gun manufactured by Emslie Tactical.",
        "name": "Alternator",
        "nameshort": "alternator",
        "class": "pilot_primary",
        "type": "smg",
    },
    "archer": {
        "desc": "Rocket Launcher with Anti-Titan lock-on.",
        "longdesc": "The Archer Heavy Rocket, also known simply as the Archer, is an anti-Titan lock-on rocket launcher manufactured by Brockhaurd Manufacturing.",
        "name": "Archer",
        "nameshort": "archer",
        "class": "pilot_at",
        "type": "anti_titan",
    },
    "car": {
        "desc": "Consistent recoil SMG.",
        "longdesc": "The Combat Advanced Round Submachine Gun (C.A.R. SMG) is a Pilot anti-personnel fully automatic submachine gun that appears in Titanfall and Titanfall 2",
        "name": "CAR",
        "nameshort": "car",
        "class": "pilot_primary",
        "type": "smg",
    },
    "coldwar": {
        "desc": "4-round burst Grenadier weapon.",
        "longdesc": "The EM-4 Cold War is a primary four-round burst bullpup grenade launcher manufactured by Vinson Dynamics, firing 4.73x33mm explosive ammunition.",
        "name": "EM-4 Cold War",
        "nameshort": "coldwar",
        "class": "pilot_primary",
        "type": "grenadier",
    },
    "defender": {
        "desc": "Charged precision beam Anti-Titan sniper.",
        "longdesc": "The Charge Rifle fires an energy beam that inflicts massive damage. Holding the trigger charges the weapon.",
        "name": "Charge Rifle",
        "nameshort": "defender",
        "class": "pilot_at",
        "type": "anti_titan",
    },
    "devotion": {
        "desc": "Ramps up fire rate over time.",
        "longdesc": "The X-55 Devotion is a light machine guns (LMGs). Its fire rate increases greatly the longer the trigger is held.",
        "name": "X-55 Devotion",
        "nameshort": "devotion",
        "class": "pilot_primary",
        "type": "lmg",
    },
    "doubletake": {
        "desc": "Twin-fire sniper rifle.",
        "longdesc": "The D-2 Double Take is a Pilot anti-personnel semi-automatic twin-barrel bullpup marksman rifle manufactured by Burrell Defense",
        "name": "D-2 Double Take",
        "nameshort": "doubletake",
        "class": "pilot_primary",
        "type": "sniper",
    },
    "epg": {
        "desc": "Single fire, direct energy propelled launcher.",
        "longdesc": "The EPG-1, or Energy Propelled Grenade, is an advanced plasma antipersonnel grenade launcher appearing in Titanfall 2. It fires slow-moving blue plasma grenades with high splash damage.",
        "name": "EPG-1",
        "nameshort": "epg",
        "class": "pilot_primary",
        "type": "grenadier",
    },
    "eva8": {
        "desc": "Fully automatic shotgun.",
        "longdesc": "The EVA-8 (Extra-Vehicular Activity) Automatic Shotgun is a Pilot anti-personnel auto-loading shotgun manufactured by Wonyeon Defense.",
        "name": "EVA-8 Auto",
        "nameshort": "eva8",
        "class": "pilot_primary",
        "type": "shotgun",
    },
    "flatline": {
        "desc": "Full-auto with a punch.",
        "longdesc": "The V-47 Flatline is a Pilot anti-personnel fully automatic bullpup assault rifle, manufactured by Wonyeon Defense. It has negligible vertical recoil, instead involving an extreme degree of horizontal recoil, similar to the Alternator.",
        "name": "V-47 Flatline",
        "nameshort": "flatline",
        "class": "pilot_primary",
        "type": "assault_rifle",
    },
    "g2a5": {
        "desc": "Semi-auto precision rifle.",
        "longdesc": "The G2A5 is a semiautomatic battle rifle manufactured by Lastimosa Armory and the successor to the G2A4 Battle Rifle. It is a Pilot primary weapon with perfect accuracy.",
        "name": "G2A5",
        "nameshort": "g2a5",
        "class": "pilot_primary",
        "type": "assault_rifle",
    },
    "hemlok": {
        "desc": "Burst-fire assault rifle.",
        "longdesc": "The M1A3 Hemlok BF-R (Burst-Fire Rifle) is a Pilot anti-personnel burst fire assault rifle.",
        "name": "Hemlok BF-R",
        "nameshort": "hemlok",
        "class": "pilot_primary",
        "type": "assault_rifle",
    },
    "kraber": {
        "desc": "Scoped heavy rifle.",
        "longdesc": "The Kraber-AP (Armor Penetrating) 14.5x114mm Sniper Rifle is a Pilot anti-personnel bolt-action heavy sniper rifle. It is manufactured by Lastimosa Armory.",
        "name": "Kraber-AP Sniper",
        "nameshort": "kraber",
        "class": "pilot_primary",
        "type": "sniper",
    },
    "leadwall": {
        "desc": "Projectile shotgun with a wide spread.",
        "longdesc": "The Leadwall is the primary Titan weapon for Ronin in Titanfall 2. It is a shotgun, based on the same design as the Triple Threat grenade launcher of Titanfall.",
        "name": "Leadwall",
        "nameshort": "leadwall",
        "class": "titan_primary",
        "type": "titan_primary",
    },
    "longbow": {
        "desc": "Semi-auto sniper.",
        "longdesc": "The D-101 Longbow-DMR (Designated Marksman Rifle) Sniper Rifle is a Pilot anti-personnel semi-automatic sniper rifle manufactured by Lastimosa Armory. The DMR is a variant of the R-101 Assault Rifle, modified into a marksman rifle role.",
        "name": "Longbow-DMR",
        "nameshort": "longbow",
        "class": "pilot_primary",
        "type": "sniper",
    },
    "lstar": {
        "desc": "Rapid fire energy LMG.",
        "longdesc": "The L-STAR (Lastimosa Armory Assault Rifle) is a Pilot anti-personnel fully automatic particle accelerating light machine gun manufactured by Lastimosa Armory.",
        "name": "L-STAR",
        "nameshort": "lstar",
        "class": "pilot_primary",
        "type": "lmg",
    },
    "mastiff": {
        "desc": "Auto-loading shotgun with wide spread.",
        "longdesc": "The M1901 Mastiff Combat Shotgun is a Pilot anti-personnel energy semi-automatic shotgun manufactured by Lastimosa Armory.",
        "name": "Mastiff",
        "nameshort": "mastiff",
        "class": "pilot_primary",
        "type": "shotgun",
    },
    "mgl": {
        "desc": "Magnetic grenade launcher.",
        "longdesc": "The MGL , also known as the Mag Launcher or Magnetic Grenade Launcher, is a Pilot anti-Titan magnetic grenade launcher manufactured by Wonyeon Defense.",
        "name": "MGL Mag Launcher",
        "nameshort": "mgl",
        "class": "pilot_at",
        "type": "grenadier",
    },
    "mozambique": {
        "desc": "Controlled spread triple barrel shotgun pistol.",
        "longdesc": "The SA-3 Mozambique, also knowns as the Mozambique Shotgun is a Pilot anti-personnel, triple-barreled shotgun pistol.",
        "name": "SA-3 Mozambique",
        "nameshort": "mozambique",
        "class": "pilot_pistol",
        "type": "pistol",
    },
    "p2016": {
        "desc": "Precision semi-auto pistol.",
        "longdesc": "The Hammond P2016 is a sidearm manufactured by Lastimosa Armory. Like its predecessor, the P2016 is a Semi-Automatic Handgun.",
        "name": "Hammond P2016",
        "nameshort": "p2016",
        "class": "pilot_pistol",
        "type": "pistol",
    },
    "splitter": {
        "desc": "Drains energy to split the shot, increasing damage",
        "longdesc": "The Splitter Rifle (Otherwise known as the Titan Particle Accelerator or TPAR)is a Titan fully-automatic energy rifle",
        "name": "Splitter Rifle",
        "nameshort": "splitter",
        "class": "titan_primary",
        "type": "titan_primary",
    },
    "predator": {
        "desc": "Heavy minigun",
        "longdesc": "Powerful minigun with a long spin-up time.",
        "name": "Predator Cannon",
        "nameshort": "predator",
        "class": "titan_primary",
        "type": "titan_primary",
    },
    "r101": {
        "desc": "Factory issue scoped predecessor of the R-201 rifle.",
        "longdesc": "The R-101C (Compact) Carbine is a Pilot anti-personnel fully automatic carbine manufactured by Lastimosa Armory.",
        "name": "R-101 Carbine",
        "nameshort": "r101",
        "class": "pilot_primary",
        "type": "assault_rifle",
    },
    "r201": {
        "desc": "Full-auto and high accuracy.",
        "longdesc": "The R-201 Special Operations Assault Rifle (SOAR) is a Pilot anti-personnel fully automatic assault rifle manufactured by Lastimosa Armory, serving as the successor to the R-101C Carbine and the predecessor to the R-301 Carbine.",
        "name": "R-201 Carbine",
        "nameshort": "r201",
        "class": "pilot_primary",
        "type": "assault_rifle",
    },
    "r97": {
        "desc": "Rapid fire SMG.",
        "longdesc": "The R-97 Compact Submachine Gun (SMG) is a Pilot anti-personnel close-quarter submachine gun manufactured by Lastimosa Armory.",
        "name": "R-97",
        "nameshort": "r97",
        "class": "pilot_primary",
        "type": "smg",
    },
    "railgun": {
        "desc": "Charges up while zoomed.",
        "longdesc": "Sniper railgun that charges up while zoomed.",
        "name": "Plasma Railgun",
        "nameshort": "railgun",
        "class": "titan_primary",
        "type": "titan_primary",
    },
    "re45": {
        "desc": ".45 cal full-auto pistol.",
        "longdesc": "The RE-45 Autopistol is a Pilot anti-personnel fully automatic machine pistol, manufactured by Lastimosa Armory and Paradinha Arsenal. It serves as a reliable 'spray-and-pray' backup sidearm for pilots at close range.",
        "name": "REEEEEEEE",
        "nameshort": "re45",
        "class": "pilot_pistol",
        "type": "pistol",
    },
    "mk6": {
        "desc": "Idiot pistol",
        "longdesc": "The next generation in AI targeting technology comes in the form of the Lastimosa Armory Smart Pistol MK6. Upgrades from the MK5 include a reciprocating charging handle, frame integrated ammo counter, multi-function Laser Aiming Module (LAM), etc.",
        "name": "Smart Pistol MK6",
        "nameshort": "mk6",
        "class": "pilot_pistol",
        "type": "pistol",
    },
    "smr": {
        "desc": "Rapidly fires micro-missiles.",
        "longdesc": "The Anti-Titan Sidewinder Micro Rocket launcher (AT-SMR), is an Anti-Titan Automatic Rocket Launcher (AT-ARL). It is manufactured by Wonyeon Defense.",
        "name": "Sidewinder SMR",
        "nameshort": "smr",
        "class": "pilot_at",
        "type": "anti_titan",
    },
    "softball": {
        "desc": "Adhesive grenade launcher.",
        "longdesc": "The R-6P Softball Anti-Armor Grenade Launcher (AAGL) is a Pilot anti-Titan/personnel grenade launcher",
        "name": "R-6P Softball",
        "nameshort": "softball",
        "class": "pilot_primary",
        "type": "grenadier",
    },
    "spitfire": {
        "desc": "Steady fire rate with a punch.",
        "longdesc": "The Spitfire Light Machine Gun (LMG) is a Pilot anti-personnel fully automatic light machine gun.",
        "name": "Spitfire",
        "nameshort": "spitfire",
        "class": "pilot_primary",
        "type": "lmg",
    },
    "t203": {
        "desc": "Ignites the impact area.",
        "longdesc": "Giant thermite grenades ignite the impact area.",
        "name": "T-203 Thermite Launcher",
        "nameshort": "t203",
        "class": "titan_primary",
        "type": "titan_primary",
    },
    "thr40mm": {
        "desc": "Semi-auto 40mm HE rounds.",
        "longdesc": "The factory issue 40mm Cannon is a semi-automatic weapon that fires a high-explosive round with good accuracy.",
        "name": "40mm Cannon",
        "nameshort": "thr40mm",
        "class": "titan_primary",
        "type": "titan_primary",
    },
    "thunderbolt": {
        "desc": "Fires a powerful ball of electricity.",
        "longdesc": "The LG-97 Thunderbolt is a Pilot anti-Titan energy projector that fires a large, slow-moving ball of electricity that causes damage to any unit within a wide radius around its flight path. Upon striking a target, it explodes in a spherical blast.",
        "name": "LG-97 Thunderbolt",
        "nameshort": "thunderbolt",
        "class": "pilot_at",
        "type": "anti_titan",
    },
    "volt": {
        "desc": "Energy actuated SMG.",
        "longdesc": "The Volt is a Pilot energy submachine gun. It is a weapon that fires concentrated bolts of high energy, which are referred to as 'blue tracers'.",
        "name": "Volt",
        "nameshort": "volt",
        "class": "pilot_primary",
        "type": "smg",
    },
    "wingman": {
        "desc": "High-powered revolver.",
        "longdesc": "The B3 Wingman is a Pilot anti-personnel revolver handgun sidearm. The Wingman boasts immense high-caliber stopping power and notable accuracy to compensate for its small magazine and relatively slow fire rate.",
        "name": "B3 Wingman",
        "nameshort": "wingman",
        "class": "pilot_pistol",
        "type": "pistol",
    },
    "wingmann": {
        "desc": "Extended range projectile pistol with stock scope.",
        "longdesc": "Bish's personal and most trusted sidearm. The B3 Wingman Elite has been customized to fit the needs of an inter-colonial arms dealer with a shady past and even cloudier business practices.",
        "name": "Wingman Elite",
        "nameshort": "wingmann",
        "class": "pilot_pistol",
        "type": "pistol",
    },
    "chaingun": {
        "desc": "20mm automatic rifle.",
        "longdesc": "20mm automatic rifle.",
        "name": "XO-16",
        "nameshort": "chaingun",
        "class": "titan_primary",
        "type": "titan_primary",
    },
}
iteration = 1000
totalTime = 0
totalMem = 0
for x in range(iteration):
    tracing_start()
    start = time.time()
    list = {
        "alternator": {
            "desc": weaponList["alternator"]["desc"],
            "longdesc": weaponList["alternator"]["longdesc"],
            "name": weaponList["alternator"]["name"],
            "nameshort": weaponList["alternator"]["nameshort"],
            "class": weaponList["alternator"]["class"],
            "type": weaponList["alternator"]["type"],
        },
        "archer": {
            "desc": weaponList["archer"]["desc"],
            "longdesc": weaponList["archer"]["longdesc"],
            "name": weaponList["archer"]["name"],
            "nameshort": weaponList["archer"]["nameshort"],
            "class": weaponList["archer"]["class"],
            "type": weaponList["archer"]["type"],
        },
        "car": {
            "desc": weaponList["car"]["desc"],
            "longdesc": weaponList["car"]["longdesc"],
            "name": weaponList["car"]["name"],
            "nameshort": weaponList["car"]["nameshort"],
            "class": weaponList["car"]["class"],
            "type": weaponList["car"]["type"],
        },
        "coldwar": {
            "desc": weaponList["coldwar"]["desc"],
            "longdesc": weaponList["coldwar"]["longdesc"],
            "name": weaponList["coldwar"]["name"],
            "nameshort": weaponList["coldwar"]["nameshort"],
            "class": weaponList["coldwar"]["class"],
            "type": weaponList["coldwar"]["type"],
        },
        "defender": {
            "desc": weaponList["defender"]["desc"],
            "longdesc": weaponList["defender"]["longdesc"],
            "name": weaponList["defender"]["name"],
            "nameshort": weaponList["defender"]["nameshort"],
            "class": weaponList["defender"]["class"],
            "type": weaponList["defender"]["type"],
        },
        "devotion": {
            "desc": weaponList["devotion"]["desc"],
            "longdesc": weaponList["devotion"]["longdesc"],
            "name": weaponList["devotion"]["name"],
            "nameshort": weaponList["devotion"]["nameshort"],
            "class": weaponList["devotion"]["class"],
            "type": weaponList["devotion"]["type"],
        },
        "doubletake": {
            "desc": weaponList["doubletake"]["desc"],
            "longdesc": weaponList["doubletake"]["longdesc"],
            "name": weaponList["doubletake"]["name"],
            "nameshort": weaponList["doubletake"]["nameshort"],
            "class": weaponList["doubletake"]["class"],
            "type": weaponList["doubletake"]["type"],
        },
        "epg": {
            "desc": weaponList["epg"]["desc"],
            "longdesc": weaponList["epg"]["longdesc"],
            "name": weaponList["epg"]["name"],
            "nameshort": weaponList["epg"]["nameshort"],
            "class": weaponList["epg"]["class"],
            "type": weaponList["epg"]["type"],
        },
        "eva8": {
            "desc": weaponList["eva8"]["desc"],
            "longdesc": weaponList["eva8"]["longdesc"],
            "name": weaponList["eva8"]["name"],
            "nameshort": weaponList["eva8"]["nameshort"],
            "class": weaponList["eva8"]["class"],
            "type": weaponList["eva8"]["type"],
        },
        "flatline": {
            "desc": weaponList["flatline"]["desc"],
            "longdesc": weaponList["flatline"]["longdesc"],
            "name": weaponList["flatline"]["name"],
            "nameshort": weaponList["flatline"]["nameshort"],
            "class": weaponList["flatline"]["class"],
            "type": weaponList["flatline"]["type"],
        },
        "g2a5": {
            "desc": weaponList["g2a5"]["desc"],
            "longdesc": weaponList["g2a5"]["longdesc"],
            "name": weaponList["g2a5"]["name"],
            "nameshort": weaponList["g2a5"]["nameshort"],
            "class": weaponList["g2a5"]["class"],
            "type": weaponList["g2a5"]["type"],
        },
        "hemlok": {
            "desc": weaponList["hemlok"]["desc"],
            "longdesc": weaponList["hemlok"]["longdesc"],
            "name": weaponList["hemlok"]["name"],
            "nameshort": weaponList["hemlok"]["nameshort"],
            "class": weaponList["hemlok"]["class"],
            "type": weaponList["hemlok"]["type"],
        },
        "kraber": {
            "desc": weaponList["kraber"]["desc"],
            "longdesc": weaponList["kraber"]["longdesc"],
            "name": weaponList["kraber"]["name"],
            "nameshort": weaponList["kraber"]["nameshort"],
            "class": weaponList["kraber"]["class"],
            "type": weaponList["kraber"]["type"],
        },
        "leadwall": {
            "desc": weaponList["leadwall"]["desc"],
            "longdesc": weaponList["leadwall"]["longdesc"],
            "name": weaponList["leadwall"]["name"],
            "nameshort": weaponList["leadwall"]["nameshort"],
            "class": weaponList["leadwall"]["class"],
            "type": weaponList["leadwall"]["type"],
        },
        "longbow": {
            "desc": weaponList["longbow"]["desc"],
            "longdesc": weaponList["longbow"]["longdesc"],
            "name": weaponList["longbow"]["name"],
            "nameshort": weaponList["longbow"]["nameshort"],
            "class": weaponList["longbow"]["class"],
            "type": weaponList["longbow"]["type"],
        },
        "lstar": {
            "desc": weaponList["lstar"]["desc"],
            "longdesc": weaponList["lstar"]["longdesc"],
            "name": weaponList["lstar"]["name"],
            "nameshort": weaponList["lstar"]["nameshort"],
            "class": weaponList["lstar"]["class"],
            "type": weaponList["lstar"]["type"],
        },
        "mastiff": {
            "desc": weaponList["mastiff"]["desc"],
            "longdesc": weaponList["mastiff"]["longdesc"],
            "name": weaponList["mastiff"]["name"],
            "nameshort": weaponList["mastiff"]["nameshort"],
            "class": weaponList["mastiff"]["class"],
            "type": weaponList["mastiff"]["type"],
        },
        "mgl": {
            "desc": weaponList["mgl"]["desc"],
            "longdesc": weaponList["mgl"]["longdesc"],
            "name": weaponList["mgl"]["name"],
            "nameshort": weaponList["mgl"]["nameshort"],
            "class": weaponList["mgl"]["class"],
            "type": weaponList["mgl"]["type"],
        },
        "mozambique": {
            "desc": weaponList["mozambique"]["desc"],
            "longdesc": weaponList["mozambique"]["longdesc"],
            "name": weaponList["mozambique"]["name"],
            "nameshort": weaponList["mozambique"]["nameshort"],
            "class": weaponList["mozambique"]["class"],
            "type": weaponList["mozambique"]["type"],
        },
        "p2016": {
            "desc": weaponList["p2016"]["desc"],
            "longdesc": weaponList["p2016"]["longdesc"],
            "name": weaponList["p2016"]["name"],
            "nameshort": weaponList["p2016"]["nameshort"],
            "class": weaponList["p2016"]["class"],
            "type": weaponList["p2016"]["type"],
        },
        "splitter": {
            "desc": weaponList["splitter"]["desc"],
            "longdesc": weaponList["splitter"]["longdesc"],
            "name": weaponList["splitter"]["name"],
            "nameshort": weaponList["splitter"]["nameshort"],
            "class": weaponList["splitter"]["class"],
            "type": weaponList["splitter"]["type"],
        },
        "predator": {
            "desc": weaponList["predator"]["desc"],
            "longdesc": weaponList["predator"]["longdesc"],
            "name": weaponList["predator"]["name"],
            "nameshort": weaponList["predator"]["nameshort"],
            "class": weaponList["predator"]["class"],
            "type": weaponList["predator"]["type"],
        },
        "r101": {
            "desc": weaponList["r101"]["desc"],
            "longdesc": weaponList["r101"]["longdesc"],
            "name": weaponList["r101"]["name"],
            "nameshort": weaponList["r101"]["nameshort"],
            "class": weaponList["r101"]["class"],
            "type": weaponList["r101"]["type"],
        },
        "r201": {
            "desc": weaponList["r201"]["desc"],
            "longdesc": weaponList["r201"]["longdesc"],
            "name": weaponList["r201"]["name"],
            "nameshort": weaponList["r201"]["nameshort"],
            "class": weaponList["r201"]["class"],
            "type": weaponList["r201"]["type"],
        },
        "r97": {
            "desc": weaponList["r97"]["desc"],
            "longdesc": weaponList["r97"]["longdesc"],
            "name": weaponList["r97"]["name"],
            "nameshort": weaponList["r97"]["nameshort"],
            "class": weaponList["r97"]["class"],
            "type": weaponList["r97"]["type"],
        },
        "railgun": {
            "desc": weaponList["railgun"]["desc"],
            "longdesc": weaponList["railgun"]["longdesc"],
            "name": weaponList["railgun"]["name"],
            "nameshort": weaponList["railgun"]["nameshort"],
            "class": weaponList["railgun"]["class"],
            "type": weaponList["railgun"]["type"],
        },
        "re45": {
            "desc": weaponList["re45"]["desc"],
            "longdesc": weaponList["re45"]["longdesc"],
            "name": weaponList["re45"]["name"],
            "nameshort": weaponList["re45"]["nameshort"],
            "class": weaponList["re45"]["class"],
            "type": weaponList["re45"]["type"],
        },
        "mk6": {
            "desc": weaponList["mk6"]["desc"],
            "longdesc": weaponList["mk6"]["longdesc"],
            "name": weaponList["mk6"]["name"],
            "nameshort": weaponList["mk6"]["nameshort"],
            "class": weaponList["mk6"]["class"],
            "type": weaponList["mk6"]["type"],
        },
        "smr": {
            "desc": weaponList["smr"]["desc"],
            "longdesc": weaponList["smr"]["longdesc"],
            "name": weaponList["smr"]["name"],
            "nameshort": weaponList["smr"]["nameshort"],
            "class": weaponList["smr"]["class"],
            "type": weaponList["smr"]["type"],
        },
        "softball": {
            "desc": weaponList["softball"]["desc"],
            "longdesc": weaponList["softball"]["longdesc"],
            "name": weaponList["softball"]["name"],
            "nameshort": weaponList["softball"]["nameshort"],
            "class": weaponList["softball"]["class"],
            "type": weaponList["softball"]["type"],
        },
        "spitfire": {
            "desc": weaponList["spitfire"]["desc"],
            "longdesc": weaponList["spitfire"]["longdesc"],
            "name": weaponList["spitfire"]["name"],
            "nameshort": weaponList["spitfire"]["nameshort"],
            "class": weaponList["spitfire"]["class"],
            "type": weaponList["spitfire"]["type"],
        },
        "t203": {
            "desc": weaponList["t203"]["desc"],
            "longdesc": weaponList["t203"]["longdesc"],
            "name": weaponList["t203"]["name"],
            "nameshort": weaponList["t203"]["nameshort"],
            "class": weaponList["t203"]["class"],
            "type": weaponList["t203"]["type"],
        },
        "thr40mm": {
            "desc": weaponList["thr40mm"]["desc"],
            "longdesc": weaponList["thr40mm"]["longdesc"],
            "name": weaponList["thr40mm"]["name"],
            "nameshort": weaponList["thr40mm"]["nameshort"],
            "class": weaponList["thr40mm"]["class"],
            "type": weaponList["thr40mm"]["type"],
        },
        "thunderbolt": {
            "desc": weaponList["thunderbolt"]["desc"],
            "longdesc": weaponList["thunderbolt"]["longdesc"],
            "name": weaponList["thunderbolt"]["name"],
            "nameshort": weaponList["thunderbolt"]["nameshort"],
            "class": weaponList["thunderbolt"]["class"],
            "type": weaponList["thunderbolt"]["type"],
        },
        "volt": {
            "desc": weaponList["volt"]["desc"],
            "longdesc": weaponList["volt"]["longdesc"],
            "name": weaponList["volt"]["name"],
            "nameshort": weaponList["volt"]["nameshort"],
            "class": weaponList["volt"]["class"],
            "type": weaponList["volt"]["type"],
        },
        "wingman": {
            "desc": weaponList["wingman"]["desc"],
            "longdesc": weaponList["wingman"]["longdesc"],
            "name": weaponList["wingman"]["name"],
            "nameshort": weaponList["wingman"]["nameshort"],
            "class": weaponList["wingman"]["class"],
            "type": weaponList["wingman"]["type"],
        },
        "wingmann": {
            "desc": weaponList["wingmann"]["desc"],
            "longdesc": weaponList["wingmann"]["longdesc"],
            "name": weaponList["wingmann"]["name"],
            "nameshort": weaponList["wingmann"]["nameshort"],
            "class": weaponList["wingmann"]["class"],
            "type": weaponList["wingmann"]["type"],
        },
        "chaingun": {
            "desc": weaponList["chaingun"]["desc"],
            "longdesc": weaponList["chaingun"]["longdesc"],
            "name": weaponList["chaingun"]["name"],
            "nameshort": weaponList["chaingun"]["nameshort"],
            "class": weaponList["chaingun"]["class"],
            "type": weaponList["chaingun"]["type"],
        },
    }

    print(list)
    print()
    print()
    print()
    print()

    end = time.time()
    totalTime += (end-start)*1000
    totalMem += tracing_mem()

print("Average stats of {0} iteration".format(iteration))
print("time elapsed {0} milli seconds".format((totalTime / iteration)))
print("peak size {0} MB".format((totalMem / iteration)))
